import turtle
Rafael = turtle.Turtle()
Rafael.color("green")
Rafael.circle(100,steps=6)
Rafael.forward(100)
Rafael.color("blue")
Rafael.circle(50)
Rafael.backward(50)
Rafael.color("red")
Rafael.circle(50)
